# Week 4 — Day 2 | Manufacturing Inventory Analysis

**Python for Supply Chain Analytics — Week 4**

This notebook applies Pandas to a manufacturing supply chain scenario. The analysis focuses on practical business questions rather than Python syntax alone.

In [1]:
import pandas as pd

## 1. Load the Dataset

Load the supplied CSV dataset into a Pandas DataFrame.

In [3]:
df = pd.read_csv("Week_4_Day_2_Manufacturing_Inventory.csv")

## 2. Inspect the Data

Review the first records and confirm the dataset dimensions.

In [4]:
df.head(5)

,Plant,Production_Line,Material,Opening_Inventory_Units,Material_Consumption_Units,Production_Quantity_Units,Safety_Stock_Units,Closing_Inventory_Units,Inventory_Status
0,Pune Manufacturing Unit,Line 1,Cold Rolled Steel Sheet,520,310,285,260,210,Below Safety Stock
1,Pune Manufacturing Unit,Line 2,Polyamide Granules,780,540,510,300,240,Below Safety Stock
2,Pune Manufacturing Unit,Line 3,Copper Busbar,430,275,260,180,155,Below Safety Stock
3,Vadodara Manufacturing Unit,Line 1,Aluminium Ingot,610,420,390,240,190,Below Safety Stock
4,Vadodara Manufacturing Unit,Line 2,Engineering Polymer Pellets,920,610,575,350,310,Below Safety Stock

In [7]:
df.shape

(12, 9)

## 3. Understand the Data Structure

Inspect the available fields before analysis.

In [9]:
df.columns

Index(['Plant', 'Production_Line', 'Material', 'Opening_Inventory_Units',
       'Material_Consumption_Units', 'Production_Quantity_Units',
       'Safety_Stock_Units', 'Closing_Inventory_Units', 'Inventory_Status'],
      dtype='object')

## 4. Select Inventory Fields

Create a focused view containing the fields needed for inventory analysis.

In [11]:
inventory_df = df[['Plant','Material','Opening_Inventory_Units','Material_Consumption_Units','Closing_Inventory_Units','Safety_Stock_Units']]
inventory_df

,Plant,Material,Opening_Inventory_Units,Material_Consumption_Units,Closing_Inventory_Units,Safety_Stock_Units
0,Pune Manufacturing Unit,Cold Rolled Steel Sheet,520,310,210,260
1,Pune Manufacturing Unit,Polyamide Granules,780,540,240,300
2,Pune Manufacturing Unit,Copper Busbar,430,275,155,180
3,Vadodara Manufacturing Unit,Aluminium Ingot,610,420,190,240
4,Vadodara Manufacturing Unit,Engineering Polymer Pellets,920,610,310,350
5,Vadodara Manufacturing Unit,Silicone Sealant,360,220,140,160
6,Chennai Manufacturing Unit,Electrical Grade Steel,740,515,225,300
7,Chennai Manufacturing Unit,Glass Fibre Reinforced Nylon,680,470,210,280
8,Chennai Manufacturing Unit,Copper Rod,510,330,180,210
9,Nashik Manufacturing Unit,Stainless Steel Coil,590,390,200,250
10,Nashik Manufacturing Unit,Thermoplastic Elastomer,840,580,260,320
11,Nashik Manufacturing Unit,Industrial Adhesive,410,265,145,170

## 5. Identify Low-Stock Materials

Business rule: closing inventory below safety stock requires attention.

In [13]:
low_stock_df = inventory_df[inventory_df['Closing_Inventory_Units'] < inventory_df['Safety_Stock_Units']]
low_stock_df

,Plant,Material,Opening_Inventory_Units,Material_Consumption_Units,Closing_Inventory_Units,Safety_Stock_Units
0,Pune Manufacturing Unit,Cold Rolled Steel Sheet,520,310,210,260
1,Pune Manufacturing Unit,Polyamide Granules,780,540,240,300
2,Pune Manufacturing Unit,Copper Busbar,430,275,155,180
3,Vadodara Manufacturing Unit,Aluminium Ingot,610,420,190,240
4,Vadodara Manufacturing Unit,Engineering Polymer Pellets,920,610,310,350
5,Vadodara Manufacturing Unit,Silicone Sealant,360,220,140,160
6,Chennai Manufacturing Unit,Electrical Grade Steel,740,515,225,300
7,Chennai Manufacturing Unit,Glass Fibre Reinforced Nylon,680,470,210,280
8,Chennai Manufacturing Unit,Copper Rod,510,330,180,210
9,Nashik Manufacturing Unit,Stainless Steel Coil,590,390,200,250
10,Nashik Manufacturing Unit,Thermoplastic Elastomer,840,580,260,320
11,Nashik Manufacturing Unit,Industrial Adhesive,410,265,145,170

## 6. Calculate Inventory Gap

Inventory Gap = Safety Stock − Closing Inventory.

In [14]:
low_stock_df['Inventory_Gap_Units'] = low_stock_df['Safety_Stock_Units'] - low_stock_df['Closing_Inventory_Units']
low_stock_df

,Plant,Material,Opening_Inventory_Units,Material_Consumption_Units,Closing_Inventory_Units,Safety_Stock_Units,Inventory_Gap_Units
0,Pune Manufacturing Unit,Cold Rolled Steel Sheet,520,310,210,260,50
1,Pune Manufacturing Unit,Polyamide Granules,780,540,240,300,60
2,Pune Manufacturing Unit,Copper Busbar,430,275,155,180,25
3,Vadodara Manufacturing Unit,Aluminium Ingot,610,420,190,240,50
4,Vadodara Manufacturing Unit,Engineering Polymer Pellets,920,610,310,350,40
5,Vadodara Manufacturing Unit,Silicone Sealant,360,220,140,160,20
6,Chennai Manufacturing Unit,Electrical Grade Steel,740,515,225,300,75
7,Chennai Manufacturing Unit,Glass Fibre Reinforced Nylon,680,470,210,280,70
8,Chennai Manufacturing Unit,Copper Rod,510,330,180,210,30
9,Nashik Manufacturing Unit,Stainless Steel Coil,590,390,200,250,50
10,Nashik Manufacturing Unit,Thermoplastic Elastomer,840,580,260,320,60
11,Nashik Manufacturing Unit,Industrial Adhesive,410,265,145,170,25

## 7. Find the Largest Inventory Gap

Identify the maximum safety-stock shortfall.

In [15]:
low_stock_df['Inventory_Gap_Units'].max()

75

## 8. Identify the Material With the Largest Gap

Locate the record corresponding to the largest observed gap.

In [17]:
low_stock_df[low_stock_df['Inventory_Gap_Units'] == 75]

,Plant,Material,Opening_Inventory_Units,Material_Consumption_Units,Closing_Inventory_Units,Safety_Stock_Units,Inventory_Gap_Units
6,Chennai Manufacturing Unit,Electrical Grade Steel,740,515,225,300,75

## 9. Calculate Inventory Coverage

Inventory Coverage % = Closing Inventory ÷ Safety Stock × 100.

In [18]:
low_stock_df['Inventory_Coverage_%'] = low_stock_df['Closing_Inventory_Units']/low_stock_df['Safety_Stock_Units']*100
low_stock_df

,Plant,Material,Opening_Inventory_Units,Material_Consumption_Units,Closing_Inventory_Units,Safety_Stock_Units,Inventory_Gap_Units,Inventory_Coverage_%
0,Pune Manufacturing Unit,Cold Rolled Steel Sheet,520,310,210,260,50,80.769231
1,Pune Manufacturing Unit,Polyamide Granules,780,540,240,300,60,80.000000
2,Pune Manufacturing Unit,Copper Busbar,430,275,155,180,25,86.111111
3,Vadodara Manufacturing Unit,Aluminium Ingot,610,420,190,240,50,79.166667
4,Vadodara Manufacturing Unit,Engineering Polymer Pellets,920,610,310,350,40,88.571429
5,Vadodara Manufacturing Unit,Silicone Sealant,360,220,140,160,20,87.500000
6,Chennai Manufacturing Unit,Electrical Grade Steel,740,515,225,300,75,75.000000
7,Chennai Manufacturing Unit,Glass Fibre Reinforced Nylon,680,470,210,280,70,75.000000
8,Chennai Manufacturing Unit,Copper Rod,510,330,180,210,30,85.714286
9,Nashik Manufacturing Unit,Stainless Steel Coil,590,390,200,250,50,80.000000
10,Nashik Manufacturing Unit,Thermoplastic Elastomer,840,580,260,320,60,81.250000
11,Nashik Manufacturing Unit,Industrial Adhesive,410,265,145,170,25,85.294118

## Business Takeaway

The analysis identifies materials below safety stock, quantifies the inventory gap, highlights the largest shortfall, and measures inventory coverage.